# Generated by Django 6.1 on 2026-08-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'รอพิจารณา'), ('Interview', 'นัดสัมภาษณ์'), ('Accepted', 'ได้ที่ฝึกงาน'), ('Rejected', 'ไม่ผ่าน')], default='Pending', max_length=20)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
