# Generated by Django 6.1 on 2026-08-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Interview', 'Interviewing'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
