# Generated by Django 6.1 on 2026-08-31 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_internship_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internship',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interviewing'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Waiting', 'Waiting for response')], default='Applied', max_length=20),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField()),
                ('interview_type', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='tracker.internship')),
            ],
        ),
    ]
