# Generated by Django 6.1 on 2026-08-31 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_internship_user_alter_internship_status_interview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='application',
            new_name='internship',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='company_name',
        ),
        migrations.AddField(
            model_name='internship',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.company'),
        ),
    ]
