# Generated by Django 6.1 on 2026-08-31 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_company_rename_application_interview_internship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='application_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='internship',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Waiting', 'Waiting for response')], default='Applied', max_length=20),
        ),
    ]
